Model:
    CharSet: [' ', 岢, 呖, 逝, 宫, 骊, 列, 倨, 使, 撬, 梅, 备, 邦, 嗣, 仔, 嘏, 斩, 渌, 椰, 尬, 最, 摆,
        替, 哔, 钦, 勇, 剃, 堠, 耪, 摘, 唇, 韧, 羌, 汹, 垃, 沏, 骆, 织, 滗, 茁, 沥, 夼, 玳, 罩, 函, 耗, 急,
        仪, 惭, 皆, 丢, 砂, 彰, 戒, s, 卩, 廷, 偎, 很, 参, 庳, 抒, 澡, 堂, 兰, 慧, 宦, 誓, 令, d, 懦, 膛,
        罔, 杀, 注, 莆, 墓, 榔, 违, 怖, 淑, 醉, 朵, 派, 寺, 咎, 偷, 云, 逾, 兑, 号, 芯, 淙, 膜, 驸, 紊, 成,
        外, 赝, 谐, 荑, 胜, 碘, 玫, 芮, 苍, 柒, 虑, 芩, 詹, 蘅, 搭, 谢, 又, 浈, 缗, 汐, 挝, 讥, 泄, 芑, 逯,
        崂, 叫, 镶, 湍, 乩, 堡, 滓, 职, 眷, 晕, 忉, 笆, 郏, 搞, 铺, 肪, 状, 卞, 单, 苷, 闺, 冈, 澶, 妈, 董,
        亍, 雍, 诗, 诈, q, 胆, 桐, 空, 愿, 杂, 郾, 吲, r, 阪, 陆, 陕, 缬, 铆, 矮, 闩, 占, 老, 儒, 莜, 郎,
        峋, 犭, 尤, 淞, 抛, 侈, 祷, 蒉, 绒, 川, 娣, 循, 惴, 孬, 木, 窒, 莎, 嵛, 荚, 龠, 力, 译, 腾, 齿, 棵,
        魄, 氯, 哐, 萑, 琅, 漆, 促, 授, 插, 平, 谪, 瞎, 胺, 饱, 辨, 蛋, 贾, 嗲, 懂, 淝, 拶, g, 渎, 阆, 炸,
        付, 峨, 据, 煤, 哂, 捶, 卦, 浼, 苫, 沃, 迩, 炔, 屁, 衷, 这, 已, 诒, 肯, 菁, 惊, 夂, 考, 惰, 蝗, 投,
        葩, 梳, 诎, 阏, 哏, 操, 骇, 篇, 椽, 稻, 糕, 饶, 剀, 芏, 切, 藤, 白, 拘, 供, 茶, 缟, 赘, 腔, 谂, 经,
        柯, 垒, 氏, 淄, 丈, 菹, 娼, 普, 掇, 歌, 幢, 诜, 髓, 尥, 噢, 迫, 悉, 薯, 漕, 冒, 彗, 謇, 刮, 吕, 薨,
        栓, 密, 溧, 澜, 嘌, 呻, 抻, 吴, 茨, 晾, 配, 闵, 己, 殃, 嬲, 匐, 共, 篡, 莱, 虫, 千, 重, 冉, 彩, 沛,
        连, 离, 裂, 瓮, 滥, 好, 艾, 堵, 荣, 冀, 联, 沼, 喟, 了, 诌, 岭, f, 莩, 禹, 浙, 性, 鞍, 彤, 运, 寤,
        湛, 陵, 幺, 碾, 绌, 闫, 伴, 脐, 变, 囗, 第, 野, 郐, 哟, 一, 皇, 坝, a, 递, 掼, 颜, 埭, 苒, 厂, 摹,
        鬃, 辩, 嵝, 醛, 咒, 去, 验, 课, 滤, 汕, 攀, 兮, 淋, 盆, 尚, 嵘, 掖, 佘, 窍, 期, 压, 石, 玲, 迨, 涛,
        陌, 璃, 戮, 遒, 谒, 荆, 祟, 世, 崔, 钵, 嘬, 伸, 嫦, 掸, 阈, 苓, 和, 扇, 史, 江, 锭, 招, 寇, 蝎, 咯,
        隋, 惩, 晨, 蕙, 昏, 灏, 筋, 阙, 锋, 姊, 娜, 准, 卉, 檄, 殖, 时, 徜, 兽, 葜, 酱, 拦, 负, 校, 呀, 拉,
        厢, 设, 台, 缓, 些, 忡, 淅, 盾, 涓, 易, 奖, 予, 似, 偿, 溟, 路, 虚, 缙, 咨, 葶, 拧, 雾, 啸, 错, 沁,
        匾, 于, 嚷, 吵, 愕, 凌, 华, 殉, 膝, 岸, 苴, 矩, 岣, 汲, 岁, 雌, 套, 崦, 嗪, 兔, 阅, 谶, 敬, 帛, 洌,
        蒂, 倏, 芙, 喷, 仡, 饣, 穗, 苠, 藩, 书, 兕, 软, 旬, 底, 判, 愀, 炮, 字, 桓, 浪, 淳, 治, 滂, 埂, 染,
        溏, 但, 骚, 蚀, 胁, 宪, 周, 默, 综, 愦, 抵, 资, 鹰, 慈, 喊, 痈, 譬, 粹, 搅, 捅, 奥, 研, 濠, 峥, 奘,
        逛, 庙, 脯, 砖, '5', 输, 题, 朗, 祝, 谣, 煞, 敲, 孝, 趟, 谧, 巩, 忿, 诤, 谀, 禄, 戳, 蒌, 倚, 迕,
        剁, 溪, 岖, 穆, 煎, 氐, 贸, 玻, 删, 伤, 悒, 枚, 痔, 拎, 辱, 癌, 迅, 岬, 狻, 毙, 峄, 獍, 铱, 竟, 翁,
        偌, 莸, 萃, 赤, 烤, 夔, 瀹, 炒, 蘼, 净, 沂, 疆, 妓, 谅, 尖, 围, 五, 猝, 喀, 冲, 崆, 伽, 颐, 洛, 叽,
        芹, 斥, 娑, 蹭, 俊, 妹, 姥, 安, 掊, 伟, 嬉, 演, 倘, 楷, 础, 咪, 执, 谖, 剧, 恃, 蔻, 睦, 偈, 寸, 坟,
        绊, 墚, 蒯, 恋, 吞, 浆, 唱, B, 蔷, 糙, 迓, 逑, 肄, 乃, 揶, 渴, 巴, 济, 司, 肝, 遛, 必, 鬼, 獗, 峤,
        墒, 逆, 抗, 逡, 霞, 屠, 浦, 恒, 昆, 鬯, 噔, 貉, 娟, 嫣, 舛, 察, 猞, 禽, 拭, 训, 遥, 悦, 渤, 壤, 裸,
        侍, 瀛, 敛, 培, 蒲, 郗, 四, 临, 鼻, 郑, 缭, 畏, 萄, 脖, 愁, 陂, 醇, 荛, 耘, 芳, 灼, 泉, 薏, 光, 沔,
        锈, 鼐, 翻, u, 跃, 媪, 荨, 幌, 玎, 扫, 哼, 牵, 泻, 幄, 绗, 鲸, 凹, 菜, 剩, 煽, 容, 缔, 就, 圬, 雅,
        呢, 赚, 灵, 馨, 歪, 蔗, 未, 隶, 钾, 录, 葙, 郊, 嗑, 玷, 捣, 逞, 拖, 梨, 乍, 蓼, 抨, 缮, 劾, 耶, 酶,
        悌, 涸, 双, 种, 泐, 协, 诺, 蓍, 莴, 噩, 踪, 鲁, 忾, 滋, 翘, A, 瓶, 超, 遭, y, 冖, 盂, 肇, 掴, 乇,
        谱, 涞, 既, 抖, 嬗, 毁, 蹿, 咛, 寄, 淌, 彪, 呤, 腺, 阿, 闸, 拓, 胤, 缀, 翔, 扩, 匏, 苹, 匿, 溉, 茅,
        汀, 巾, 诶, 缱, 堋, 骅, 另, 粉, 特, 晶, 径, 赊, 睫, 召, 吓, 袒, 崮, F, 尾, 丐, 灶, 吩, 户, 娃, 轿,
        昭, 巽, 瘫, 稠, 卜, 磐, 奠, 溴, 塥, 阶, 訇, 歇, 莶, 侉, 郓, 眉, 剡, 喔, 噶, 谓, 捍, 衅, 侵, 祥, 绁,
        益, 猛, 愎, 澄, 渍, 扣, 黎, 坎, 等, 塬, 欢, 汛, 珍, 圪, 灾, 廓, 贝, 亲, 青, 斯, 般, 茈, 呵, 油, 茏,
        洪, 少, 腐, 莪, 群, 徇, 是, 颂, 萋, w, 缥, 寞, 航, 管, 漓, 浃, 瀣, x, 玑, 榷, 草, 纱, 蚤, 太, 桨,
        赡, 蠕, 釉, 塾, 告, 桅, 动, 毅, 傻, 帕, 篓, 妊, 刳, 叶, 缈, 邑, 撙, H, 羚, 粗, 梧, 谴, 维, 涝, 蕤,
        畚, 修, 侮, 纪, 萸, 偏, 奸, 欧, 谦, 肮, 绵, 窖, 诡, 娉, 贯, 涿, 臃, 遨, 迹, 僵, 莅, 尢, 莹, 弈, 拽,
        俳, 找, 骁, 入, 洲, 缏, 南, 萎, 查, 骏, 亭, 葬, 帽, 闼, 皋, 佰, 兜, 办, 倪, 创, 撰, 帐, 妮, 瓣, 宋,
        绡, n, 蕨, 搂, 簇, 沐, 散, 湮, 房, 雇, 茴, 露, 党, 郴, 寂, 镀, 堇, 献, G, 淀, 谰, 缨, 奇, 啡, 啷,
        理, 飘, 崴, 收, 骓, 铣, 总, 朽, 蜗, 褐, 馔, 讵, 缄, 咩, 彝, 蛙, 犯, 导, 劂, 猫, 钱, 叛, 营, 叱, 允,
        先, 骄, 百, 咿, 夷, 梯, 绨, 当, 嬖, 知, 窗, 郯, 鹊, 茕, 撮, 糜, 囤, 盘, 剖, 诹, 陇, 坍, 哨, 讷, 峰,
        逃, 眩, 倥, 缝, 缪, 宝, 姝, 襄, 饥, 舶, 戊, 鳞, 源, 氖, 嫜, 咳, 渝, '8', 忠, 永, 嗜, 孕, 恰, 园,
        短, 锤, 多, 彷, 洞, 粟, 揞, 佟, 媲, 濯, 被, 败, 廿, 疯, 渭, 圯, 褪, 叮, 船, 窃, 口, 痘, 截, 钳, 本,
        住, 剐, 弹, 酬, 棋, 绻, 苣, 停, 瘁, 挪, 宇, 凿, 毯, 剞, 岐, 垫, 慊, 匝, 桃, 衣, 饬, 媳, 哩, 丨, 邓,
        M, 悛, 漏, 疏, 媛, 驶, 迪, 讪, 坩, 郝, 铂, 阍, 栈, 缂, 援, 红, 徕, 漳, 加, 霜, 悝, 次, 虽, 炭, 舰,
        苑, 畴, 毓, 谷, 猿, 烈, 挖, 芈, 轻, 莽, 狙, 前, 卢, 捕, 啥, 茔, 概, 惫, 馈, 酝, 诿, 娄, 坼, 眠, 铝,
        绰, 液, 九, K, 财, 娓, 绕, 致, 焉, 反, 阄, 篆, 懿, 骂, 情, 卯, 捞, 卵, 狠, 阝, 完, 佳, 箔, 东, 闯,
        炯, C, 干, 噫, 怀, 堕, 漤, 诳, 涌, 内, 目, 藿, 懵, 沤, 滦, 钎, 诨, 俾, 延, 卧, 科, 壑, 亻, 转, 肚,
        姗, 钠, 半, 分, 囊, 菝, 莺, 嗦, 茆, 鼓, 曝, 竭, 崩, 瘴, 傥, 垆, 脏, 论, 褥, 赣, 舆, 怕, 搏, 怆, 隙,
        随, 息, 钢, 潍, 却, 元, 挛, 攻, 俺, 铅, 嗡, 溆, 绔, 需, 跋, 膘, 侧, 鄢, 芍, 墀, 岌, 宄, 龟, 杨, 嗯,
        蛇, 翅, 滠, 拈, 慷, 咕, 鼗, 绮, 涠, 撸, 啵, 涂, 箱, 哧, 缫, 郄, 倭, 淡, 什, 垦, 幼, 侔, 鸥, 还, 蓓,
        首, 针, 蹬, 瞳, 抡, 浏, 缆, 惺, 沾, 炽, 七, 苛, 溢, 悖, 烹, 粘, 菀, 屋, 撑, 坑, 辽, 仗, '2', 细,
        臀, 申, 挚, 鲍, 钡, 乱, 割, 苦, 讣, 图, 仟, 腹, 用, 憧, 颅, 蟹, 哗, 韩, 砚, 啼, 氵, 遄, 掩, 湃, 柬,
        沣, 燎, 萁, 嘧, 坪, 赏, 颧, 部, 笺, 诫, 苘, 纫, 看, 贤, 汔, 苎, 舅, 炬, 克, 誊, 乜, 啻, 乡, 虾, 馊,
        侣, 漂, 儋, 饩, 萱, 舷, 距, 愧, 巛, 嘈, 众, 岙, 依, 嘤, 嗉, 吾, 央, 舟, 芡, 俪, 借, 酌, 犰, 獠, 殊,
        谟, 照, 趾, 楞, 旨, 沉, 北, 仆, 原, 贫, '7', 猊, 蛊, 便, 垩, 唾, 渫, 俅, 腊, 靡, 笑, 儡, 菇, 弗,
        匈, 肌, 歉, 垛, 靛, 忪, 偃, 谘, 怒, 展, 师, 蓄, 啄, 犁, 摩, 坡, 涮, 度, 茼, 抬, 棕, 吹, 夜, 槐, 垲,
        谏, 绱, 章, 犴, 督, 业, 掠, 啪, 接, 塘, 嘲, 逅, 麓, 稿, 苌, 猸, 躺, 悼, 教, 鳖, 订, 讲, 挺, 溺, 戌,
        蹈, 架, 脱, 蒈, 彘, 摇, 奴, 嗍, 届, T, 旱, 阃, 你, 芤, 子, 绢, 揉, 崧, 徊, 谄, 娴, 沮, 料, 陔, 氰,
        袁, 唐, 毫, 雹, 啃, 枢, 刭, 绍, R, 葺, 械, 柔, 孳, 慕, 新, 砷, 劫, 湾, 委, 仁, 拱, 饨, 猪, 亨, 庐,
        舱, 凰, 逼, 篱, 妙, 狸, 侬, 俎, 廾, 闳, 私, 再, 攮, 假, 午, 侃, 矗, 铀, 困, 廛, 荬, 抠, 怠, 蜘, 说,
        串, 嚯, 欠, 农, 扪, 苯, 拙, 纵, 提, 轰, 言, 缍, 冯, 价, 磁, 胯, 亢, 嫖, 杖, 镜, 亥, 站, 山, 罗, 马,
        巢, 铜, 锰, 迂, 院, 痢, 芽, 欺, 咋, 崎, 樱, S, 走, 禺, 呷, 法, 圹, 撤, 缚, 藻, 黄, 量, 洫, 方, 鹤,
        潞, 靠, 筒, 皂, 咽, 旅, 靴, 丝, 瞪, 官, 歧, 捆, 屿, 蕻, 讯, 嫩, 失, 嘿, 际, 豆, 藏, 桥, 劝, 芨, 素,
        扦, 悲, 置, 忮, 疙, 稳, 忤, 托, 仉, 疮, 胀, 菔, 健, 靶, 纳, 暑, 盏, 欣, 陟, 福, 祁, 雀, 孔, 亦, 茄,
        衡, 缯, 脑, 粒, 顷, 汾, 奏, 屡, 挎, 疑, 应, 搜, 孤, 庄, 籍, 淤, 娶, 骗, 嵯, 茑, 憷, 缤, 橙, 浞, 蓟,
        犹, 卷, 互, 鞠, 骸, 杠, 伦, 鞭, 撩, 擒, 岈, 集, 奶, 澹, 爷, 蔬, 迳, 擢, 板, 询, 拍, 艰, 勐, 门, 俟,
        姬, 丛, 谲, 挫, 节, 诋, 模, 感, 词, 扮, 饯, 芎, 枝, 惠, 嗅, 沿, 鹅, 臆, 墉, 锹, 泼, 浣, 颓, 戈, 泡,
        绽, 线, 嘴, 驯, 蒽, 乘, 茎, 妒, 廒, 圭, 塑, 纾, 将, 胰, 忙, 班, 羞, 芫, 鄞, 痰, 拇, 冻, U, 郫, 弥,
        薄, 凶, 仄, 冂, 美, 尼, 涩, 刑, 食, 几, 岗, 厘, 沙, 缧, 呃, 静, 坏, 邪, 敢, 们, 才, 驿, 壁, 泳, 佻,
        缺, 浊, 邸, 瀑, 栽, 残, 蝇, 暇, 幸, 谆, 碧, 缘, 侯, 盯, 仕, 鸭, 曹, 悴, 骤, 丁, 寮, 壅, 现, 橇, 惜,
        芷, 儆, 婀, 降, 疥, 佾, 栏, 陋, 踊, 惝, 徽, 匕, 枕, 赫, 篮, 与, 砸, 哜, 弘, 汞, 形, 相, 佥, 难, 沧,
        荻, 品, 复, 谔, 叟, 煌, 钮, 愣, 蓬, 簧, 臼, 邂, 缛, 俣, 渔, 豢, 拥, 阼, 罚, 徐, 膊, 崇, 廴, 葭, 擞,
        丿, 斟, 冬, 膏, 回, 徭, 窘, 旁, 缸, 幂, 碌, 卒, 许, 嵩, 闶, 湿, 屎, 挡, 份, 顽, 哿, 奉, 堞, 兆, 佴,
        壕, 盛, 盟, 痪, 姚, 惮, 馆, 咝, 毒, 狄, 淖, 揭, 限, 渲, 撵, 渊, 纶, 卟, 噌, 孩, 樊, 春, 茉, 中, 恿,
        仝, 阗, 吭, 绩, 甙, 侄, 坳, 偾, 琶, 珂, 浜, 烩, 囔, 肆, p, 小, 芴, 府, 苡, 疗, 河, 色, 绠, 途, 哉,
        菱, 迦, 厌, 婧, 淠, 圻, 徙, 寰, 贬, 喉, 嘁, 霓, 疲, 池, 萍, 擀, 苗, 隅, 窝, 噙, 猓, 偶, 咬, 扳, 汇,
        抱, 溯, 荡, 蚂, 歼, 称, 劳, 厩, 扁, 墟, 荼, 嫘, 厦, 肉, 沩, 铡, 茜, 倒, 婵, 盈, 结, 婚, 添, 嚆, 墁,
        逋, 化, 警, 讦, 屺, 文, 酚, 瀚, 勖, 凇, 厣, 码, 稗, 蕞, 挞, 牢, 堙, 功, 邋, 兴, 低, 婊, 垣, 吃, 立,
        阖, 惧, 室, 馕, '9', 交, 巡, 蓖, 恪, 迮, 勒, 悻, 厝, 雁, 狈, 系, 技, 制, 戏, 省, 蹇, 蔼, 勉, 嫌,
        蚜, 倬, 芝, 蛰, 仙, 每, 绂, 奈, 浑, 缑, 掏, 末, 猜, 罕, 护, 哝, 挢, 映, 蕉, 玟, 潮, 家, 崃, 酉, 凉,
        呒, 诘, 敌, 肥, 婆, 愤, 嫱, 逄, 尘, 薅, 袄, 皱, 哑, 怪, 劣, 愠, 黉, 惕, 擐, 缒, 貌, 擎, 爱, 唯, 暮,
        崤, 驽, 霖, 暂, 鸿, 捎, 窟, 划, 患, 碳, 诖, 逻, 棺, 腑, 位, 肘, 卑, 豁, 猩, 死, 睾, 邢, 拾, 冠, 储,
        芪, 荮, 缇, 证, 莠, 叔, 噻, 佩, 岛, 浴, 蚊, 剔, 尸, 探, 猎, 浒, 棘, 窄, 裴, 尜, 溶, 陀, 遍, 绣, 哌,
        圳, 卸, 崾, 志, 忆, 菠, 媒, 思, 汊, 寒, 傅, 拢, 桶, 售, 市, D, 熬, 诃, 额, 芘, 姐, 飧, 颖, 汨, 填,
        猱, 耽, 臻, 箩, 得, 女, 阡, 揄, 藉, 俱, 馅, 暹, 菽, 盐, 兹, 骒, 剌, 匹, 晚, 烘, 哥, 芊, 体, 熟, 乓,
        澧, 评, 疹, 筏, 炊, 诟, 伶, 秤, 後, 忍, 趴, 踢, 精, 豫, 蚕, 旦, 拊, 炼, 阔, 改, 拿, 缕, 瓤, 焚, 瓢,
        领, 逶, 吱, 疽, 嚎, 垅, 藓, 辖, 继, 闱, 城, 奋, 界, 庋, 下, 坠, 晌, 傲, 茌, 清, 呱, 乙, 艇, 尺, 癣,
        菥, 洁, 绛, 请, 刻, 袖, 壮, 人, 伺, 匙, 鸡, 峡, 徉, 希, 遮, 洇, 鄙, 雪, 獯, 沽, 浓, 扛, 庸, 京, 苊,
        晤, 苕, 灯, 没, 祖, 唔, 锑, 夯, 缳, 彡, 甩, 荩, 芦, 渖, 恳, 踌, 如, 讧, 陬, 溱, 裔, 墩, 措, 埽, 洧,
        葱, 抢, 缌, 揖, 郢, 柑, 蔫, 酸, 深, 陪, 诏, 岜, 迁, 薛, 朔, 螺, 耸, 股, 呦, 村, 闭, 烧, 妆, 墙, 全,
        腋, 噤, 琳, 唛, 张, 豹, 菊, 载, 梦, 建, 丕, 衙, 荤, 帜, 约, 推, 舒, 淬, 迸, 坞, 矢, 债, 蒜, 莞, 勰,
        萜, 裙, 杭, 馀, 诚, 团, 案, 薪, 蘖, 逍, 谚, 响, 豳, 辜, 糟, 蓁, v, 钩, 富, 帘, 风, 爽, 涕, 顺, 岱,
        轴, 醒, 刎, 绿, 朴, 夺, 恕, 涉, e, 疟, 钞, 热, 为, 聊, 送, 蕾, 扔, 泰, 咆, 溃, 葸, 犷, 真, 芒, 捺,
        锥, 堤, 弋, 植, 激, 妯, 馁, 阎, 氦, 甸, 瞢, 确, 吆, 肢, 躬, 彭, 缲, 侑, 佑, 宴, 挤, 扌, 杉, 砧, 落,
        绥, 闻, 固, 秃, 阽, 诂, 拜, 殿, 诉, 囱, 漠, 惬, 心, 努, 疾, 肺, 卫, 峦, 余, 嫠, 啦, 邈, 韶, 摄, 妫,
        摺, 肃, 徘, 洳, 椅, 藁, 恼, 甯, 把, 腻, 施, 沦, 水, 琼, 丬, 险, 冥, 奚, 泥, k, 捱, 彖, 识, 垂, 颠,
        签, 晃, 岔, 玩, 妗, 寿, 采, 捩, 翱, 哙, 页, 郜, 俑, 吨, 揠, 潇, 慵, 堪, 岵, 独, 嗟, 弛, 括, 仓, 嵌,
        蜜, 萏, 秒, 捉, 枷, 刨, 乏, 擗, 驾, 事, 驷, 叹, 粕, 炕, 段, 型, 洗, 面, 搔, 迷, 迟, 宿, 悭, 仲, 愫,
        涣, 盲, 凯, 夹, 牛, 猬, 獬, 烦, 镣, 鞘, 问, 挨, 琢, 读, 藕, 蛾, 块, 糯, 嶷, 德, 肩, 受, 巍, 掳, 呲,
        秧, 蕴, 徨, 荷, 我, 凫, 堍, 沸, 规, 狗, 衔, 炙, 刹, 皮, 阚, 霉, 爻, E, 翼, 圆, 伊, 噍, 芄, 怜, 灸,
        揿, 檀, 瘦, 渐, 翰, 讴, 勾, 绶, 盗, 席, 氓, 苄, 孀, 堰, 冢, 票, 蜕, 猾, 岷, 闲, 锯, 锨, 念, 丶, 诓,
        传, 副, 搬, 换, 虐, 芭, 棱, 较, 埠, 躁, 婕, 吧, 拨, 茂, 睡, 莘, 峒, 喜, 缜, 率, 瞄, 透, 洮, 顶, 鲜,
        篙, 男, 定, 圣, 阋, 粱, 撼, 尴, 饺, 杆, 牌, 哞, 矣, 效, 夥, 诼, 瞥, 同, W, 爿, 甲, 携, 劁, 哄, 嘟,
        纲, 晒, 浔, 榆, 娆, 渑, 秽, 叻, 磋, 稍, 枣, 喹, 魏, 湘, 溘, 彦, 喇, 辅, 罢, 遂, 薤, b, 巅, 悔, 实,
        扰, 骐, 讠, 钉, 囝, 嘘, 喈, 弓, 忄, 搐, 宀, 蓉, 辣, 赋, 悱, 册, 馓, 嘭, 劭, 傩, 归, 齐, 咔, 熔, 贩,
        绚, 颗, Y, 榨, 专, 藐, 止, 杜, 赁, 呛, 颈, 哒, 寓, 翌, 鄣, 林, 痊, 观, 拐, 婪, 长, 孛, 喱, 谑, 曰,
        椭, 忝, 睛, 惹, 浅, 昂, 狭, 讽, 镁, 檬, 嗥, 帧, 月, 叵, 哽, 守, 洚, 斗, 蕲, 捷, 葑, 员, 甾, 俯, 忒,
        渺, 坊, 砰, 菪, 嘞, 姒, 跨, 奕, 印, 剂, 直, 丰, 莨, 猕, 移, 纸, 喑, 鄄, 繁, 盒, 潦, 慨, 萘, 悚, 孜,
        式, 苁, 胃, 姜, 侗, 阊, 饲, 环, 雷, 组, 阀, 妇, 募, 卤, 弁, 椒, 拮, 智, 绦, 层, 滞, 茫, 矛, 飞, 轮,
        葡, 醋, 场, 铰, 瑰, 磨, 灰, 骞, 玢, 屹, 饭, 租, 以, 勹, 唰, 倌, 愚, 何, 绋, 嗤, 哆, 辆, 骡, 迥, 脂,
        胬, 剜, 劲, 啊, 绾, 终, 驵, 蔽, 不, 兄, 哺, 濞, 舌, 瀵, 的, 策, 冷, 嗷, 身, 杏, j, 狼, 脾, 蒙, 鸽,
        嘹, 汁, 遁, 郡, 轨, 株, 溽, 刂, 恨, 趁, 比, 越, 袭, 咀, 粤, 鬲, 孱, 谎, 阒, 拷, 擦, 绷, 某, 此, 湓,
        磺, 懊, 屉, 佗, 囟, 咐, 款, 蓝, 李, 馇, 茸, 矫, 冁, 行, 栅, 姣, 乳, 妥, 客, 倡, 蜂, 雨, 车, 救, 廪,
        肿, 柏, 巳, 痴, 咄, 崭, 薇, 秩, 噱, 县, 计, 适, 幞, 巨, 噎, 珈, 鼙, 捂, 刈, 踏, 绘, 酃, 掌, h, 洽,
        势, 俞, 痉, 蕺, 士, 撇, 敖, 哭, 鼎, 嗒, 怯, 珏, 葚, 裁, 姑, 扑, 崛, 年, 溅, 忌, 泪, 破, 赎, 楼, 祈,
        帚, 赵, 岘, 释, 登, 遽, 熄, 珙, 岚, 公, 孚, 诲, 链, 呐, 噪, 匀, 苋, 芬, 恍, 鱼, 雄, 埔, 咣, 谩, 蹦,
        迤, 岑, 裤, 獾, 洵, 预, 烂, 爆, 甫, 遗, 暴, 蘸, 手, 认, 庞, 蕹, 宰, 闷, 莼, 廑, P, 诮, 纠, 乒, 妤,
        差, 呸, 悄, 谥, 店, 避, 冗, 哚, 骈, 艽, 孥, 奢, 淘, 掀, 驰, 咖, 罐, 嘶, 妻, 痹, 厍, 俦, 范, 忭, 嗽,
        队, 蹲, 头, 赜, 尝, 忖, 姨, 咧, 慰, 苜, 融, 龄, 匍, 话, 拗, 足, 亓, 乌, 阻, 孟, 劐, 廖, 褂, 埃, 擤,
        惆, 哦, 垮, 纽, 磊, 岍, 严, 惯, 寡, 发, 嗖, 猢, 保, 谛, 惘, 邻, 潆, 毋, 缉, 佼, 缃, 香, 味, 具, 佬,
        呶, 嚅, 举, 胎, 炎, 敦, 茧, 巧, 温, 辫, 宠, 桩, 辑, 记, 沌, 敝, 卣, 僧, 郦, 射, 浍, 滏, 排, 纂, 坛,
        谜, 棠, 汶, 棉, 涨, 顿, 噬, 堀, 值, 柿, 蓊, 叭, 摊, 议, 放, 闪, 畿, 跺, 络, 倜, 珑, 搪, 沅, 抹, 赂,
        取, 药, 氮, 槽, 猥, 想, 缅, 陷, 龚, 凸, 邰, 涑, 驻, 偕, 戚, 对, 厥, 奂, 矾, 揸, 阮, 挽, 父, 嗄, 衢,
        寨, 畔, 信, 怅, 亿, 意, 捭, 筛, 娈, 脸, 簿, 钟, 坭, 蓦, 圈, 靥, 堆, 恫, 宸, 刃, 趣, 贺, 沫, 毡, 肖,
        存, 汆, 颁, 崽, 屑, 胚, 掣, 眨, 芗, 吻, 诙, 番, 者, 善, 荧, 掷, 哇, 悃, 触, 缦, 纺, 卮, 屏, 影, 即,
        摧, 僭, 蓐, 浚, 微, 伎, 汉, 嗫, 挟, 武, 坌, 程, 酪, 帆, 会, 匚, 浯, 倾, 隆, 怂, 啖, 夙, 圩, 妞, 咭,
        蘩, 苇, 稼, 珠, 亩, 详, 甘, 绲, 豌, 绐, 脓, 耀, 券, 芜, 亘, 洹, 珀, 僚, 夕, 茹, 且, 攒, 澳, 垡, 陨,
        苻, 萌, 撞, 婴, 凛, 妲, 娲, 茇, 镭, 钻, 殴, 嗔, 嫉, 荭, 辰, 病, 氨, 遐, 桑, 耍, 塄, 婷, 舵, 豪, 遘,
        曳, 构, 质, 类, 纹, 冶, 汩, 皑, 忏, 彻, 宽, 臣, 迎, 妨, 抟, 僖, 蕈, 揍, 锻, 丧, 邃, 奔, 倦, 肠, 茛,
        饽, 潢, 穴, 谮, 邕, 撕, 讳, 两, 缢, 钙, 躲, 拒, 栋, 片, 虏, 视, 写, 嗌, 痕, 颇, 乐, 汝, 逗, 版, 弯,
        舍, 漭, 狮, 掮, 远, 间, 谫, 态, 饪, 指, 撺, 芾, 污, 碱, 报, 描, 凼, 驮, 弑, 攘, 战, 唤, 灌, 馍, 哪,
        淦, 龋, 锗, 闾, 屙, 剑, 幻, 侦, 芥, 由, 唷, 狡, 娇, m, 竞, 涎, 宙, 舜, 吐, 谋, 兀, 赦, 速, 喁, 犀,
        宓, 撷, 在, 壳, 端, 讼, 母, 项, 峭, 监, 尽, 土, 巫, 蜡, 裳, 袜, 佶, 累, 厶, 踞, 铃, 弦, 充, 浇, 皖,
        莓, 攉, 啾, 频, 抚, 侥, 聚, 畦, 惨, 潜, 淮, 巯, 凡, 喘, 弟, 莳, 坦, 萤, 艿, 耐, 佣, 劓, 蔚, 伞, 嫂,
        吠, 秘, 庵, 抄, 姘, 疤, 菸, 渥, 凄, 挠, 猗, 楔, 蓿, 嘉, 逸, 渚, 工, 犊, 着, 磷, 壹, 友, 任, 鄯, 驭,
        役, 筷, 薰, 辈, 凑, 褰, 艘, 憬, 秀, 嵴, 支, 刿, 绺, 咚, 揪, 牟, 湄, 角, 陧, 咂, 彳, 揽, 疵, 睹, 阉,
        倍, 币, 涵, 仨, 滔, 谵, 毖, 缡, 灞, 尉, 毕, 惚, 恢, 嗨, 烁, 造, 馗, 甭, 僻, 诵, 盼, 丸, 覆, 陉, 陛,
        莒, 谊, 劢, 烟, 勤, 右, 燃, 傺, 谳, 荸, '6', 嘣, 婢, 履, 韦, 濂, 丌, 商, 邯, 秦, 偻, 缋, 夸, 椎,
        边, 酣, 啶, 坤, 彼, 哀, 蒇, 瓷, 上, 咫, 醚, 骨, 寻, 骀, 籴, 通, 妾, 凭, 能, 刷, 隘, 律, 拚, 钝, 姆,
        优, 嶙, 钥, 斧, 须, 爪, 莫, 社, 刀, 康, 俩, 瓦, 羡, 季, 亚, 无, 坶, 媚, 俏, 免, 劬, 娱, 练, 嗝, 涪,
        黔, 霸, 蛛, 揲, 戎, 驳, 滩, 谈, 酥, 刍, 诠, 庭, 医, 潘, 承, 喾, 伐, 谌, 蔡, 撂, 姓, 勋, 滢, 嵋, 贞,
        蒋, 苟, 剽, 恐, 珉, 装, 汰, 鹿, 邾, 艺, 崞, 谙, 邮, 黑, 匦, 盖, 牙, 笛, 么, 岫, 攥, 吮, 芟, 帅, 瑟,
        礁, 拼, 瘟, 粪, 址, 表, 愉, 挂, 局, 菖, 闹, 呙, 僳, 碴, 久, 床, 典, 灿, 沟, 嘀, 孺, 孓, 墼, 泞, 卿,
        牡, 竣, 磕, 僬, 及, 坂, 餐, 从, 览, 试, 选, 锣, 佃, 阑, 碗, 显, 哕, 始, 辙, 峁, 宗, 辉, 箍, 遣, 按,
        嬷, 胖, 叩, 膳, 广, 捌, 咻, 地, 姿, 侠, 馘, 莰, 氽, 俚, 废, 瞻, 封, 耿, 吖, 踩, 垤, 日, 勃, 谕, 酷,
        蘧, 步, 拳, 英, 莲, 秆, 酞, 藜, 疫, 玮, 虹, 碎, 绞, 珊, 涟, 硅, 零, 诩, 海, 阌, 垭, 阂, 兢, 嫁, 绫,
        赴, 折, 琴, 电, 熊, 郸, 徒, 匠, 究, 墨, 然, 酮, 花, 贡, 瞧, 剿, 嶂, 圮, 穿, 诸, 害, N, 星, 断, 靖,
        赓, 赔, 尻, 逖, 媸, 斜, 咴, 掂, 非, 崖, 圃, 菰, 镰, 叉, 诬, 谁, 孰, 孪, 伍, 婺, 嗬, 陶, 权, 蜒, 自,
        嚼, t, 兼, 诔, 勺, 杯, 早, 焦, 到, 呈, 涧, 嗵, 枫, 吉, 恽, 播, 赢, 匮, 滑, 吣, 俸, 梁, 穷, 处, 菡,
        硕, 胶, 啜, 库, 儇, 爬, 梢, 盅, 刊, 肋, 娌, 辕, 幕, 逵, 缴, 核, 甄, 含, 喝, 虞, 仿, 阕, 陈, 梗, 蕃,
        涯, 旗, 稀, 敞, 斋, 晦, 侩, 谝, 硬, 博, 鞋, 学, 呗, 怨, 诅, 吒, 烯, 昧, 抑, 膺, 爸, 缁, 枯, 缵, 缎,
        仍, 嗓, 弄, 衬, 诱, 游, 嗳, 窜, 赶, 裕, 汗, 购, 驹, 补, 阢, 纬, 萝, 韵, 耙, 街, 够, 堑, X, 匣, 材,
        俜, 税, 瓜, 饴, 茚, 脆, 丹, 遢, 忱, 州, 洎, 庠, 唁, 纭, 常, 艳, 慑, 刺, 仑, 俨, 弧, 桔, 淹, 苤, 卓,
        厕, 悍, 纤, 哎, 溥, 奁, 菏, 袍, 诞, 冕, 噘, 鄹, 噜, 徂, 畅, 笔, 咤, 井, 隧, 聪, 饧, 釜, 宕, 驴, 唉,
        幛, 防, 挹, 媾, 溲, 来, 钨, 贰, 廊, 冤, 八, 酒, 萦, 担, 突, 只, 菩, 悸, 竿, 肛, 菘, 汤, 义, 亮, 唠,
        贿, 汜, 邹, 快, 郧, 卺, 孑, 咦, 虎, 宅, 费, 揣, 嵬, 盎, 尕, 孢, 娅, 胳, 屯, 开, 馑, 矍, 呔, 慌, 混,
        侨, 那, 秸, 附, 寥, 苈, 斑, 呋, 跑, 瞬, 啤, 尧, 胸, 粮, 珥, 暗, 伪, 访, 洄, 抽, 惶, 奄, 咱, 可, 匆,
        喂, 牧, 氛, 介, 虱, 乖, 摔, 蛔, 眼, 宜, 寐, 浩, 焕, 岩, 遴, 腿, 账, 卅, 毛, 澎, 炉, 阱, 懒, 谠, 馐,
        拔, 樟, 谇, 僮, 诽, 捐, 捻, 哲, 夏, 钒, 燮, 烙, 蹄, 谡, 统, 啬, 讶, 壬, 魔, 持, 布, 疚, V, 峙, 点,
        控, 族, 乾, 鸦, 滴, 厮, 粳, 朝, 荜, 脚, 惟, 贪, 庑, 谭, 喋, 搓, 袱, 画, 习, 憾, 境, 也, 娩, 血, 傧,
        湫, 天, 嫡, 掎, 掬, 擂, 麻, 扯, 合, 辟, 寝, 廨, 其, 倮, 赞, 戕, 都, 烫, 关, 泛, 潭, 溻, 嫒, 斡, 捃,
        憨, 缰, 喃, 宏, 童, 嚓, 捋, 屐, 恭, 顾, 弊, 该, 禾, 茬, 浠, 懈, 搽, 邵, 喽, 蒎, 湎, 脊, 饰, 辞, '3',
        酵, Q, 绀, 幽, 居, 呕, 沆, 米, 衫, 嵊, 扭, 松, 腥, 幔, 萆, 猹, 怃, 晴, 诰, 蚁, 碍, 至, 阜, 湔, 喙,
        侏, 湟, 略, 滇, 测, 擅, 亟, 栖, 拴, 岳, 挥, 叨, 逢, 宥, 辛, 噗, 故, 侪, 纰, 强, 饫, 纯, J, 哳, 景,
        荪, 濉, 退, 嫔, 搴, 碑, 酆, 谯, 押, 伲, 燕, 异, 标, 徼, 庇, 吡, 锚, 背, 菟, 焰, 赐, 诣, 疼, 庆, 追,
        嗾, 级, 高, 掭, 苔, 之, 葆, 芸, 忸, 坚, 玖, 夤, 握, 逭, 陡, 姹, 耷, 咏, 凵, 觅, 垢, 濡, 魂, 档, 祭,
        揩, 唬, 痛, 骋, 朱, 薷, 港, 珐, 浮, 桌, 泊, 昼, 鸳, 吝, 句, 廉, 并, 纷, 拟, c, 坷, 返, 汴, 倩, 有,
        横, 扒, 獭, 痞, 萼, 鹃, 嘎, 睬, 逊, 澈, 眯, 泵, 芰, 烷, 赌, 滟, 懔, 烽, 十, 算, 郇, 要, 獐, 庖, 馄,
        稚, 危, 道, 嵫, 逦, 砍, 涫, 岽, 良, 忻, 衰, 障, 休, 韭, 哓, 帷, 鄱, 镐, 艹, 幡, 极, 惦, 辶, 蹋, 氢,
        鸯, 涔, 乔, 怄, 蘑, 绉, 偬, 粥, 菅, 咸, 溷, 隳, 彐, 垄, 卡, 庥, 籽, 荽, 勘, 骖, 郅, 帝, 椿, 仃, 解,
        舀, 笨, 享, 聘, 森, 紫, 绯, 驼, 郛, 悠, 徵, 刚, 坫, 蕖, '4', 嫫, 辔, 丫, 坜, 鸵, 糖, 活, 锌, 洙,
        忧, 赃, 涡, 搁, 估, 凳, 夭, 庹, 焙, 辗, 庾, 耻, 饷, 示, 糠, 噼, 匪, 症, 荒, 仂, 淇, 洼, 波, 伯, 坨,
        抓, 旧]
    ImageChannel: 3
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: D:\project\dddd_trainer\练习平台17题验证码生成器源码&EXE\训练图片生成
    Project: test_17
    Val: 0.03
Train:
    BATCH_SIZE: 64
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.97, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 64
    TEST_STEP: 1000
