Model:
    CharSet: [' ', '1', D, Q, F, R, P, '5', '9', '6', X, G, H, S, V, Z, '3', T, K,
        J, W, '2', '8', '4', U, Y, E, I, C, B, L, A, '7']
    ImageChannel: 1
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: C:\Users\12460\Downloads\1112\images
    Project: test_3
    Val: 0.03
Train:
    BATCH_SIZE: 32
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.97, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 32
    TEST_STEP: 1000
